### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by mtdavidson** [phaza/laravel-postgis#1]
Hi Just saw your new package and have been trying it out I've got the application setup and connecting to the database but am having some trouble with the migrations. 

I am getting the following exception 

     Argument 1 passed to CreateTestTable::{closure}() must be an instance of Phaza\LaravelPostgis\Schema\Blueprint, instance of Bosnadev\Database\Schema\Blueprint given, called in /path/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php on line 110 and defined   

could you spread some light on this my migration is as follows

    <?php
    
    use Illuminate\Support\Facades\Schema;
    use Phaza\LaravelPostgis\Schema\Blueprint as Blueprint;
    use Illuminate\Database\Migrations\Migration;
    
    class CreateTestTable extends Migration {
    
        /**
         * Run the migrations.
         *
         * @return void
         */
        public function up()
        {
            Schema::create('test', function(Blueprint $table)
            {
                $table->increments('id');
                $table->point('point');
                $table->timestamps();
            });
        }
    
        /**
         * Reverse the migrations.
         *
         * @return void
         */
        public function down()
        {
            Schema::drop('test');
        }
    
    }

Thanks in advance,

Mark

**Comment by phaza** [comment]
Try now.

This package isn't really ready yet, there lots of integrations tests missing, but if you still want to try, I'd love your feedback.

**Comment by mtdavidson** [comment]
Great stuff Peter appreciate the quick response. Migration now seems to work as expected wasn't able to use the enablePostgis method though as I am running version 9.1 of Postgres think you need > 9.1 for it work. 

Apprecaite its early days but the pacakge is looking great I was actually just starting work on my own package to add better postgis support than in the previous package I'd used ( https://github.com/greglamb/laravel-postgis-database ) when I stumbled accross yours so will definitely be giving you some feedback.

**Comment by jubairsaidi** [comment]
I know this issue was seemingly solved but I'm getting the same error as above?
