### ISSUE TITLE
MultiPolygon Parsing, polygons require two entries

### ISSUE THREAD

**Issue by claytical** [phaza/laravel-postgis#12]
I imported a shape file using shp2pgsql that contains MultiPolygons. When I try to retrieve them from the database, I get these two errors:

InvalidArgumentException in MultiPolygon.php line 19: $polygons must contain at least two entries

and

ParserException in Parser.php line 43: Parsing failed: $polygons must contain at least two entries

In the model, it doesn't matter how the $postgisFields are defined: MultiPolygon, Polygon or GeometryCollection, I still get the same error.

**Comment by phaza** [comment]
Hi,

this is unfortunately a bug/issue in the [geo-io/wkb-parser] package.
It doesn't really matter what you define in $postgisFields (the type is not being used after we switched to that package).

You could try filing an issue there, just show the WKB data (the hex-like data you see in the database) and the error you get.

An alternative is to cast the MultiPolygon to a Polygon in the database, but that's a workaround, not really a solution.

[geo-io/wkb-parser]: https://github.com/geo-io/wkb-parser

**Comment by jsor** [comment]
Hi @phaza,

could you explain why this is a bug in the wkb parser? The geometry is a multipolygon which contains a single polygon:

```
MULTIPOLYGON(((-80.214554 25.769598 0 0,-80.2147 25.774514 0 0,-80.212983 25.77456 0 0,-80.212977 25.773597 0 0,-80.211448 25.773655 0 0,-80.211498 25.774579 0 0,-80.209432 25.774665 0 0,-80.209392 25.773667 0 0,-80.204387 25.773834 0 0,-80.199383 25.774324 0 0,-80.197718 25.774031 0 0,-80.197757 25.774975 0 0,-80.193655 25.775108 0 0,-80.193623 25.774134 0 0,-80.191855 25.772551 0 0,-80.193442 25.76969 0 0,-80.192231 25.768345 0 0,-80.192879 25.758009 0 0,-80.196301 25.759985 0 0,-80.195608 25.76152 0 0,-80.198856 25.761454 0 0,-80.200646 25.763287 0 0,-80.20401 25.763164 0 0,-80.204023 25.76367 0 0,-80.205673 25.763141 0 0,-80.214326 25.762935 0 0,-80.214451 25.765883 0 0,-80.214539 25.768649 0 0,-80.216203 25.76858 0 0,-80.214554 25.769598 0 0)))
```

Not sure if i miss something but this looks valid to me and the wkb parser extracts it correctly. Why does your MultiPolygon class require at least 2 polygons?

**Comment by phaza** [comment]
I'm very sorry, @jsor.
It was a mistake on my part where I seemed to recall something which wasn't correct.

I've fixed the issue and pushed out a new version (2.11), so this should now be fixed.
Let me know if you still have problems.

**Comment by jsor** [comment]
Cool! No need to be sorry and thanks for using my library :smiley:

**Comment by vasimshk** [comment]
hi,
I am getting this error.
not sure, whats the solution to this. 
Can someone please let me know
