### ISSUE TITLE
JSON serialization order

### ISSUE THREAD

**Issue by claytical** [phaza/laravel-postgis#13]
I noticed that the jsonSerialize function in Point.php returns in the order of Latitude, Longitude to conform to ISO 6709, but then looking at the GeoJSON standard it's the other way around (http://geojson.org/geojson-spec.html#positions).

Are there plans to be able to specify order/standard from the model?

Also, thanks for making this package, it's been a life saver!

**Comment by phaza** [comment]
Ping @MetalMatze.

There are no plans to support different orders, but I know Matthias added json serialising specifically for GeoJSON, so I presume it'll make sense to swap the order. Anyway, hopefully @MetalMatze will come by and give his point of view.

**Comment by MetalMatze** [comment]
You're right, I've used GeoJSON as json standard. 
That's why I'm swapping it, because there it is used in that order. 

We could of course add somehow the option to switch it back. But I would make the option opt-in and use GeoJSON by default.

**Comment by phaza** [comment]
@MetalMatze but that's the point, you've mixed the order of the attributes.
GeoJSON asks for lonlat, not latlon.
https://github.com/phaza/laravel-postgis/blob/master/src/Geometries/Point.php#L71

Or does the Point class from the GeoJSON package swap them?

**Comment by MetalMatze** [comment]
You could be right. :smile: 

http://geojson.org/geojson-spec.html#id2
Says it's the LngLat.

**Comment by phaza** [comment]
I'm currently not using this feature, and is busy with project, but if one
of you create a patch with a test, I'll merge it.

**Comment by MetalMatze** [comment]
Oh, thanks for fixing my mistake! :heart: :relaxed:
