### ISSUE TITLE
Other DATUM 

### ISSUE THREAD

**Issue by daniloaluiz** [phaza/laravel-postgis#14]
Hello,
I tried to make the migration:
  $ table-> point ('point', 31982) -> nullable ();
             $ table-> polygon ('drawing', 31982);
My Datum is SIRGAS 2000, but the bank is:
   geography point (Point, 4326)
   geography drawing (Polygon, 4326) NOT NULL,
You have no way to change the DATUM for what I need?

**Comment by phaza** [comment]
We're using geographies in Postgis, and Postgis only supports SRID 4326 for geography types.
http://postgis.net/docs/manual-1.5/ch04.html#Geography_Basics

In the future, if we decide to support geometries as well, or if Postgis finally gets support for other SRIDs, it'll make sense to specify other SRID.

For now I can only recommend you convert to 4326 if you want to use this package.

**Comment by daniloaluiz** [comment]
There is some foresight to launch a version with support for geometry?

**Comment by phaza** [comment]
Not at the moment, but if you make a pull request I'll merge it.
Basically you'll only need to change the blueprint and postgis grammar I think.
Everything else should work out of the box.
