### ISSUE TITLE
Blueprint type incompability

### ISSUE THREAD

**Issue by varakh** [phaza/laravel-postgis#15]
hi @phaza,

you did great things here, but I am having an issue related to blueprints.

I am using slimframework with illuminate/eloquent orm.

The following "migration" code (which works for all other tables perfectly) has problems with the blueprint type.

```
Capsule::schema()->dropIfExists('locations');
        Capsule::schema()->create('locations', function(\Phaza\LaravelPostgis\Schema\Blueprint $table) {
            $table->enablePostgis();
            $table->increments('id');
            $table->point('location');
            $table->polygon('polygon');
            $table->timestamps();
        });
```

```
PHP Catchable fatal error:  Argument 1 passed to LocationMigration::{closure}() must be an instance of Phaza\LaravelPostgis\Schema\Blueprint, instance of Illuminate\Database\Schema\Blueprint given, called in /home/alexander/Arbeitsplätze/slim-api/vendor/illuminate/database/Schema/Builder.php on line 129 and defined in /home/alexander/Arbeitsplätze/slim-api/app/data/updates_migrations/LocationMigration.php
```

**Comment by phaza** [comment]
Have you made sure you load the service provider and db is set to pgsql?

**Comment by varakh** [comment]
The DB is set to pgsql with CapsuleManager. I don't know where to load the serviceprovider. Do you have any experience with adding laravel serviceproviders to the slim framework?

**Comment by phaza** [comment]
Nah, I don't know anything about slim. Sorry, but there's your problem at
least.
