### ISSUE TITLE
PHP Version Required?

### ISSUE THREAD

**Issue by gmcmicken** [phaza/laravel-postgis#22]
This package's composer req. list PHP 5.5, is this correct? Many online deployment platforms (I'm using openshift online), only support PHP 5.4.

Thanks,

**Comment by phaza** [comment]
Hi, sorry for the late reply.

We're using ::class all over the code for type safety.
PHP 5.4 is end of life in one month, so no reason to sacrifice type safety to support that.

I know it's not always easy to change hosts, but I'd recommend going for someone who keeps up with recent PHP releases.
