### ISSUE TITLE
What is the necessity of explicitly defining what type a geo field is?

### ISSUE THREAD

**Issue by rogue780** [phaza/laravel-postgis#23]
The library can be very easily modified to make it so instead of 

    protected $postgisFields = [
        'location' => Point::class,
        'polygon' => Polygon::class,
    ];

you can instead use

    protected $postgisFields = [
        'location',
        'polygon',
    ];

just as well since the object type is already deduced when decoding the WKB.

Would you be open to a PR that makes this change?

**Comment by phaza** [comment]
Yes. I'm aware of it, it's a relic from the past that I haven't gotten
around fixing. PR very welcome!
