### ISSUE TITLE
\Illuminate\Support\Arr::isAssoc() no longer exists.

### ISSUE THREAD

**Issue by kyestork** [phaza/laravel-postgis#25]
The Eloquent PostgisTrait throws an error.

**Comment by phaza** [comment]
Seems to exist both in master and 5.1
https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Arr.php#L274
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Arr.php#L285

Maybe you can elaborate on how you're getting the error?

**Comment by kyestork** [comment]
Y'know what? Figured it out. I'm holding to 5.0.* in my `composer.json`. It's not in the 5.0 branch.

**Comment by phaza** [comment]
Ah yeah, thanks. I'll probably just require 5.1. It's stable and LTS.
Leaving this open till I fix the composer.json.

**Comment by kyestork** [comment]
Cool, thanks, and I just upgraded Laravel. Works just fine now.

**Comment by phaza** [comment]
New version out which requires 5.1
