### ISSUE TITLE
Framework v5.2.7 breaks with `createFactory()` compatability error

### ISSUE THREAD

**Issue by jonnybarnes** [phaza/laravel-postgis#32]
Specifically the error is with `bosnadev/database` package, I get the error:

```
[2016-01-12 20:56:09] local.ERROR: ErrorException: Declaration of Bosnadev\Database\Connectors
\ConnectionFactory::createConnection($driver, PDO $connection, $database, $prefix = '', array
$config = Array) should be compatible with Illuminate\Database\Connectors\ConnectionFactory::c
reateConnection($driver, $connection, $database, $prefix = '', array $config = Array) in /User
s/jonny/Development/git/jbl5/vendor/bosnadev/database/src/Connectors/ConnectionFactory.php:13
```

How can we work out what the incompatibility is?

**Comment by jonnybarnes** [comment]
It’s the `PDO $connection` part. Maybe its because I’m using PHP7, but if I change `PDO $connection` to just `$connection` then I get no errors. This needs to be done in both this package and the Bosnadev package.

**Comment by Maiti** [comment]
I have the same error after ```php artisan migrate:refresh --seed``` 
php 5.6.14 
laravel 5.2.10

**Comment by phaza** [comment]
Hi, I'm aware of the problem, I just haven't decided how to handle it yet.
If I change the function signature, it'll break compatibility with with L5.1, which has LTS.

I'll probably have to maintain two versions, which I'm not too happy about.

**Comment by jonnybarnes** [comment]
I assume the easiest way of doing that would be to bump the package version, people using L5.1 can keep using v2.x, people using L5.2 can use v3.x?

It’d just be a pain keeping feature parity between the two versions. :/

**Comment by phaza** [comment]
The other problem was that the postgres package I was depending on hasn't updated. But I found a fork that seems to be well maintained, so I based it on that.

Anyway, 3.0 is out for L5.2. Please try and report any problems.

**Comment by jonnybarnes** [comment]
3.0 works on Laravel 5.2 for me. :)

**Comment by Lamp27** [comment]
@phaza What about 5.1 version? Still not fixed.

**Comment by jadjoubran** [comment]
You might have to clear your compiled.php file
It happened to me while upgrading from Laravel 5.1 to 5.2
