### ISSUE TITLE
How to seed a point?

### ISSUE THREAD

**Issue by Malraoosh** [phaza/laravel-postgis#45]
I need to seed a point, I tried to use the Accessor of an attribute of type postgres point.
In the db seeder, I just want to pass the lat long, while in the accessor, I am converting them to postgres geometry point format.

Here is the Accessor I am trying to use in the User model:

    public function setSourceLatLongAttribute($value)
        {
            $latlong = explode(" ", $value);
            $latitude = $latlong[0];
            $longitude = $latlong[1];
            $this->attributes['source_lat_long'] = DB::raw("ST_SetSRID(ST_MakePoint($latitude, $longitude), 4326)");
        }

and I just want to save the location in the seeder like this:

    $users = [
            [
                'name' => 'Admin Istrator',
                'email' => 'admin@admin.com',
                'password' => bcrypt('1234'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed' => true,
                'source_lat_long' => "31.9566 35.9457",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
    DB::table(config('access.users_table'))->insert($users);

What I expected is to have the Accessor called once I run the db seeder, but I got an error from the postgres db:

     [Illuminate\Database\QueryException]
      SQLSTATE[XX000]: Internal error: 7 ERROR:  parse error - invalid geometry
      HINT:  "31.9566 " <-- parse error at position 8 within geometry

    
      [PDOException]
      SQLSTATE[XX000]: Internal error: 7 ERROR:  parse error - invalid geometry
      HINT:  "31.9566 " <-- parse error at position 8 within geometry

So, the question is, can I use the Accessor to help me in this task of db seeding? or, how would I get the valid geometry to seed with?

**Comment by jadjoubran** [comment]
Hi @Malraoosh 
You can just import `Point` at the top of your file by adding:

```
use Phaza\LaravelPostgis\Geometries\Point;
```

and then you could say:

```
    'location'     => new Point($faker->latitude, $faker->longitude),
```

or replace $faker->latitude with your own

**Comment by dazjohnson** [comment]
Did this solve your problem? I've got the same issue but the suggested fix doesn't work.
`'location' => new Point(51.16257,-0.58042),`
In the model I've got:
```
    protected $postgisFields = array(
        'location' => Point::class,
    );
```
And I'm getting error:
```
[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[XX000]: Internal error: 7 ERROR:  parse error - invalid geometry
  HINT:  "-60.518132 " <-- parse error at position 11 within geometry

  [PDOException]
  SQLSTATE[XX000]: Internal error: 7 ERROR:  parse error - invalid geometry
  HINT:  "-60.518132 " <-- parse error at position 11 within geometry

```

**Comment by tezrik** [comment]
use PostgisTrait; in model

**Comment by veceraj** [comment]
Hi @dazjohnson

Using PostgisTrait in model does not help either.

The newly created Point is parsed as String and due to that is in incorrect form.

Using the **toWKT** method worked for me.

`'location' => (new Point(51.16257,-0.58042))->toWKT(),`

**Comment by dpgalloway** [comment]
Thanks @veceraj for the workaround. I'm not sure why this was closed because I'm still having the same issue 3 years later.
