### ISSUE TITLE
CALL FOR MAINTAINERS

### ISSUE THREAD

**Issue by phaza** [phaza/laravel-postgis#50]
Unfortunately I'm no longer working for the company where I was using/maintaining this project. I'm no longer doing PHP either, but it seems quite many rely on this project. And instead of it dying along with my commitment, I'm hoping someone will be willing to take over ownership?

Any takers?

**Comment by njbarrett** [comment]
Hi phaza, I am working on a project which will see my using this project a lot. I am willing to put forward my time into maintaining it to some extent.

**Comment by jonnybarnes** [comment]
I’d be happy to help in any way I can

**Comment by phaza** [comment]
I've initiated a transfer to @njbarrett. I've added you both as collaborators. I really hope you can keep this rolling as it seems to be a quite popular package.

**Comment by njbarrett** [comment]
Thanks @phaza . I will do my best to keep it going. I will definitely need to implement additional methods like "contains()" and "insersects()" etc
